[project]
name = "lab3-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "scipy>=1.16.0",
    "seaborn>=0.13.2",
]
